// ============================================================================
// Ranch Manager Pro — Equipment fuel/service logging integration tests (bun test)
//
//   DATABASE_URL=postgresql://postgres@127.0.0.1:5433/ranch_tasks_test \
//     bun test src/server/equipmentLogging.test.ts
//
// What this file truly tests
// --------------------------
// The write endpoints (`logFuel` / `logMaintenance` in src/server/equipment.ts)
// are TanStack Start server FNs: in raw TypeScript source bun only sees the
// compiled client facades ({ url, method, __executeServer }), and the real
// handler body lives behind a build-time virtual module
// (`#tanstack-start-server-fn-resolver`, generated by the vite plugin), so the
// handlers cannot be invoked directly from `bun test` without a full app build.
// Calling the facades instead resolves to `undefined` handlers, so this suite
// tests the same code the handlers themselves run:
//
//   1. the REAL exported validation functions the handlers execute on every
//      request — `parseFuelLogInput` and `parseMaintLogInput` (imported from
//      ./equipment, NOT local mimics) — including required-field and
//      type/range rules;
//   2. the operation-scoping contract the handlers rely on (INSERT…SELECT…
//      WHERE equipment.id AND equipment.operation_id = auth.operationId, which
//      makes a cross-ranch mutation match zero rows) against a REAL local
//      Postgres, seeded with two operations + one unit each;
//   3. pure client helpers the modals use: `fuelTotalCents` and the
//      draft-includes functions.
//
// Guard: refuses to run against anything that isn't a local Postgres, so the
// owner's Neon is never touched by this file.
// ============================================================================
import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { runMigrations } from "../../db/migrate";
import { closeDb, sql } from "~/db";
import { parseFuelLogInput, parseMaintLogInput } from "~/server/equipment";
import { fuelTotalCents } from "~/types/equipment";
import { fuelDraftIncludes, serviceDraftIncludes } from "~/components/equipment/TrackingModals";

type TestDb = ReturnType<typeof sql>;

let db: TestDb;
let opAId: number;
let opBId: number;
let eqAId: number; // Ranch A's truck
let eqBId: number; // Ranch B's truck (must be invisible to A's writes)

beforeAll(async () => {
  const url = process.env.DATABASE_URL ?? "";
  if (!/127\.0\.0\.1/.test(url)) {
    throw new Error(
      "equipmentLogging.test.ts requires a LOCAL test Postgres (DATABASE_URL with 127.0.0.1). " +
        "See the local-postgres-testing skill; the owner's Neon must never be used."
    );
  }
  db = sql();
  await runMigrations(); // idempotent; includes 0004_equipment.sql + 0014 scoping
  const [a] = await db<[{ id: number }]>`INSERT INTO operations (name) VALUES ('Equipment Test Ranch A') RETURNING id`;
  const [b] = await db<[{ id: number }]>`INSERT INTO operations (name) VALUES ('Equipment Test Ranch B') RETURNING id`;
  opAId = a.id;
  opBId = b.id;

  // One unit per ranch — the cross-ranch target the isolation asserts on.
  const [ea] = await db<[{ id: number }]>`
    INSERT INTO equipment (operation_id, name, category, hours, miles)
    VALUES (${opAId}, 'A Work Truck', 'truck', 1200, 86000) RETURNING id`;
  const [eb] = await db<[{ id: number }]>`
    INSERT INTO equipment (operation_id, name, category, hours, miles)
    VALUES (${opBId}, 'B Work Truck', 'truck', 500, 30000) RETURNING id`;
  eqAId = ea.id;
  eqBId = eb.id;
});

afterAll(async () => {
  // Operations cascade-delete every scoped row (equipment → fuel_log +
  // maintenance_records via ON DELETE). Idempotent if a test failed midway.
  try {
    await db`DELETE FROM operations WHERE id = ${opAId} OR id = ${opBId}`;
  } catch {
    /* best effort */
  }
  try {
    await closeDb();
  } catch {
    /* best effort */
  }
});

// The exact SQL the logFuel handler runs (INSERT … SELECT scoped through the
// equipment row, so a machine from another ranch matches zero rows). Kept here
// as the DB-level assertion of the scoping contract; the handler body itself
// executes only inside a compiled app (see header comment).
const logFuelScoped = (
  operationId: number,
  equipmentId: number | null,
  gallons: number,
  costCents: number | null
) =>
  db<[{ id: number }]>`
    INSERT INTO fuel_log (operation_id, equipment_id, fuel_date, fuel_type, gallons, cost_cents, location, notes)
    SELECT ${operationId}, CASE WHEN ${equipmentId}::int IS NULL THEN NULL ELSE ${equipmentId}::int END,
           '2026-09-04', 'diesel', ${gallons}, ${costCents}, 'Main tank', 'fall fill'
    WHERE ${equipmentId}::int IS NULL
       OR EXISTS (SELECT 1 FROM equipment e WHERE e.id = ${equipmentId}::int AND e.operation_id = ${operationId})
    RETURNING id`;

// The exact SQL the logMaintenance handler runs (INSERT … SELECT FROM
// equipment e WHERE e.id AND e.operation_id = auth.operationId).
const logMaintScoped = (
  operationId: number,
  equipmentId: number,
  description: string,
  vendor: string
) =>
  db<[{ id: number }]>`
    INSERT INTO maintenance_records (operation_id, equipment_id, service_date, service_type, description,
                                     cost_cents, meter_hours, meter_miles, status, next_due_date,
                                     next_due_hours, next_due_miles, vendor)
    SELECT ${operationId}, ${equipmentId}, '2026-09-04', 'oil-change', ${description},
           6500, 1200, 86000, 'done', '2026-12-04',
           1300, NULL, ${vendor}
    FROM equipment e
    WHERE e.id = ${equipmentId} AND e.operation_id = ${operationId}
    RETURNING id`;

// ---------------------------------------------------------------------------
// Fuel logging — operation-scoped writes (the logFuel DB contract)
// ---------------------------------------------------------------------------

describe("logFuel scoping contract — a fill persists only for same-ranch equipment", () => {
  test("accepts a valid equipment_id from the same ranch and persists the fill", async () => {
    const [row] = await logFuelScoped(opAId, eqAId, 48.5, 18371);
    expect(row.id).not.toBe(0);

    const [f] = await db<[{ id: number; operation_id: number; gallons: string; cost_cents: number }]>`
      SELECT id, operation_id, gallons, cost_cents FROM fuel_log WHERE id = ${row.id}`;
    expect(Number(f.operation_id)).toBe(opAId);
    expect(Number(f.gallons)).toBe(48.5);
    expect(f.cost_cents).toBe(18371);
  });

  test("allows a NULL equipment_id (bulk tank top-up)", async () => {
    const [row] = await logFuelScoped(opAId, null, 250, 90000);
    expect(row.id).not.toBe(0);
    const [f] = await db<[{ equipment_id: number | null }]>`
      SELECT equipment_id FROM fuel_log WHERE id = ${row.id}`;
    expect(f.equipment_id).toBeNull();
  });

  test("REJECTS a cross-ranch equipment_id — the scoped SELECT matches zero rows (A cannot log fuel on B's truck)", async () => {
    const rows = await logFuelScoped(opAId, eqBId, 10, 4000);
    expect(rows.length).toBe(0);
    // Positive control: B's truck is real and reachable under B's operation.
    const [bCheck] = await db<[{ id: number }]>`
      SELECT id FROM equipment WHERE id = ${eqBId} AND operation_id = ${opBId}`;
    expect(bCheck.id).toBe(eqBId);
  });

  test("the operation-scoped read can see A's fills but never B's", async () => {
    const aFuel = await db`SELECT id FROM fuel_log WHERE operation_id = ${opAId}`;
    const bFuel = await db`SELECT id FROM fuel_log WHERE operation_id = ${opBId}`;
    expect(aFuel.length).not.toBe(0); // the two A fills above
    expect(bFuel.length).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Maintenance logging — operation-scoped writes (the logMaintenance DB contract)
// ---------------------------------------------------------------------------

describe("logMaintenance scoping contract — a service persists only for same-ranch equipment", () => {
  test("accepts a valid equipment_id from the same ranch and persists the service", async () => {
    const [row] = await logMaintScoped(opAId, eqAId, "Oil + filter", "Bob's Shop");
    expect(row.id).not.toBe(0);

    const [m] = await db<[{ id: number; operation_id: number; service_type: string; vendor: string }]>`
      SELECT id, operation_id, service_type, vendor FROM maintenance_records WHERE id = ${row.id}`;
    expect(Number(m.operation_id)).toBe(opAId);
    expect(m.service_type).toBe("oil-change");
    expect(m.vendor).toBe("Bob's Shop");
  });

  test("REJECTS a cross-ranch equipment_id — INSERT…SELECT FROM equipment matches nothing (A cannot service B's truck)", async () => {
    const rows = await logMaintScoped(opAId, eqBId, "Repair", "Shop B");
    expect(rows.length).toBe(0);

    // Positive control: B's truck is real and reachable under B's operation.
    const [bCheck] = await db<[{ id: number }]>`
      SELECT id FROM equipment WHERE id = ${eqBId} AND operation_id = ${opBId}`;
    expect(bCheck.id).toBe(eqBId);
  });

  test("the operation-scoped read sees A's record and never B's", async () => {
    const aMaint = await db`SELECT id FROM maintenance_records WHERE operation_id = ${opAId}`;
    const bMaint = await db`SELECT id FROM maintenance_records WHERE operation_id = ${opBId}`;
    expect(aMaint.length).not.toBe(0);
    expect(bMaint.length).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// The REAL validation functions the handlers execute on every request
// ---------------------------------------------------------------------------

describe("parseFuelLogInput — the validator logFuel runs on every fill (real function)", () => {
  test("requires a fuel date in YYYY-MM-DD", () => {
    expect(() => parseFuelLogInput({ gallons: 48.5 })).toThrow("Fuel date is required");
    expect(() => parseFuelLogInput({ fuel_date: "09/04/2026", gallons: 48.5 })).toThrow(
      "Dates must be in YYYY-MM-DD format."
    );
  });

  test("requires gallons > 0 and finite (rejects zero, blank, negative, non-numeric)", () => {
    const base = { fuel_date: "2026-09-04" };
    expect(() => parseFuelLogInput({ ...base, gallons: 0 })).toThrow("Gallons must be greater than zero.");
    expect(() => parseFuelLogInput({ ...base, gallons: -3 })).toThrow("Gallons must be greater than zero.");
    expect(() => parseFuelLogInput({ ...base, gallons: "" })).toThrow("Gallons must be greater than zero.");
    expect(() => parseFuelLogInput({ ...base, gallons: "abc" })).toThrow("Gallons must be greater than zero.");
  });

  test("parses a valid fill: equipment optional, date kept, cost clamped at zero, blanks → null", () => {
    const out = parseFuelLogInput({
      equipment_id: 12,
      fuel_date: "2026-09-04",
      fuel_type: "gasoline",
      gallons: "48.5",
      cost_cents: "18371",
      location: "  Main tank  ",
      notes: "",
    });
    expect(out.equipment_id).toBe(12);
    expect(out.fuel_date).toBe("2026-09-04");
    expect(out.fuel_type).toBe("gasoline");
    expect(out.gallons).toBe(48.5);
    expect(out.cost_cents).toBe(18371);
    expect(out.location).toBe("Main tank");
    expect(out.notes).toBeNull();
  });

  test("unknown fuel_type defaults to diesel; negative/blank cost clamps to null or 0", () => {
    const base = { fuel_date: "2026-09-04", gallons: 10 };
    expect(parseFuelLogInput({ ...base, fuel_type: "jet-fuel" }).fuel_type).toBe("diesel");
    expect(parseFuelLogInput({ ...base, cost_cents: -500 }).cost_cents).toBe(0);
    expect(parseFuelLogInput({ ...base, cost_cents: "" }).cost_cents).toBeNull();
    expect(parseFuelLogInput({ ...base, equipment_id: "" }).equipment_id).toBeNull();
  });
});

describe("parseMaintLogInput — the validator logMaintenance runs on every service (real function)", () => {
  test("requires a service date and an equipment pick", () => {
    expect(() => parseMaintLogInput({})).toThrow("Service date is required (YYYY-MM-DD).");
    expect(() => parseMaintLogInput({ service_date: "2026-09-04" })).toThrow("Pick the equipment this service is for.");
    expect(() => parseMaintLogInput({ service_date: "2026-09-04", equipment_id: "" })).toThrow(
      "Pick the equipment this service is for."
    );
  });

  test("parses a valid service: cost in cents, meters optional, defaults applied", () => {
    const out = parseMaintLogInput({
      equipment_id: 7,
      service_date: "2026-09-04",
      service_type: "oil-change",
      description: "  Oil + filter  ",
      cost_cents: "6500",
      meter_hours: 1200,
      meter_miles: 86000,
      status: "done",
      next_due_date: "2026-12-04",
      vendor: "Bob's Shop",
    });
    expect(out.equipment_id).toBe(7);
    expect(out.service_type).toBe("oil-change");
    expect(out.description).toBe("Oil + filter");
    expect(out.cost_cents).toBe(6500);
    expect(out.meter_hours).toBe(1200);
    expect(out.meter_miles).toBe(86000);
    expect(out.status).toBe("done");
    expect(out.next_due_date).toBe("2026-12-04");
    expect(out.vendor).toBe("Bob's Shop");
  });

  test("meter values must be non-negative; unknown types/status fall back to defaults", () => {
    const base = { service_date: "2026-09-04", equipment_id: 7 };
    expect(() => parseMaintLogInput({ ...base, meter_hours: -5 })).toThrow("Meter hours can't be negative.");
    expect(() => parseMaintLogInput({ ...base, meter_miles: -1 })).toThrow("Meter miles can't be negative.");
    expect(parseMaintLogInput({ ...base, service_type: "weird" }).service_type).toBe("other");
    expect(parseMaintLogInput({ ...base, status: "weird" }).status).toBe("done");
    expect(parseMaintLogInput({ ...base, cost_cents: -2 }).cost_cents).toBe(0);
    expect(parseMaintLogInput(base).meter_hours).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Pure client logic — total-cost calc + draft-includes helpers
// ---------------------------------------------------------------------------

describe("fuelTotalCents — gallons × price per gallon (auto-computed total)", () => {
  test("computes the total in cents", () => {
    expect(fuelTotalCents(48.5, 3.79)).toBe(18382); // 48.5 × 3.79 = 183.815 → 18382
  });

  test("is 0 for a zero gallon or zero price entry", () => {
    expect(fuelTotalCents(0, 3.79)).toBe(0);
    expect(fuelTotalCents(20, 0)).toBe(0);
  });

  test("never returns negative — clamps at 0", () => {
    expect(fuelTotalCents(-5, 3)).toBe(0);
    expect(fuelTotalCents(5, -1)).toBe(0);
  });

  test("returns NaN for half-typed / blank inputs so the UI shows '—'", () => {
    expect(Number.isNaN(fuelTotalCents(Number.NaN, 3))).toBe(true);
    expect(Number.isNaN(fuelTotalCents(0, Number.NaN))).toBe(true);
    expect(Number.isNaN(fuelTotalCents(Number.POSITIVE_INFINITY, 3))).toBe(true);
  });
});

describe("tracking-form draft helpers (draft-includes)", () => {
  test("an untouched fuel draft does not count as a draft", () => {
    expect(
      fuelDraftIncludes({
        equipment_id: null,
        fuel_date: new Date().toISOString().slice(0, 10),
        gallons: "",
        pricePerGal: "",
        fuel_type: "diesel",
        meter_hours: "",
        meter_miles: "",
        location: "",
        notes: "",
      })
    ).toBe(false);
  });

  test("typing gallons, price, location, or notes marks the draft", () => {
    const base = {
      equipment_id: null,
      fuel_date: new Date().toISOString().slice(0, 10),
      gallons: "",
      pricePerGal: "",
      fuel_type: "diesel",
      meter_hours: "",
      meter_miles: "",
      location: "",
      notes: "",
    };
    expect(fuelDraftIncludes({ ...base, gallons: "48.5" })).toBe(true);
    expect(fuelDraftIncludes({ ...base, pricePerGal: "3.79" })).toBe(true);
    expect(fuelDraftIncludes({ ...base, location: "Main tank" })).toBe(true);
    expect(fuelDraftIncludes({ ...base, notes: "winter blend" })).toBe(true);
  });

  test("an untouched service draft does not count as a draft", () => {
    expect(
      serviceDraftIncludes({
        equipment_id: null,
        service_date: new Date().toISOString().slice(0, 10),
        service_type: "scheduled",
        cost: "",
        vendor: "",
        next_due_miles: "",
        next_due_hours: "",
        next_due_date: "",
        description: "",
      })
    ).toBe(false);
  });

  test("typing cost, vendor, next-due, or description marks the draft", () => {
    const base = {
      equipment_id: null,
      service_date: new Date().toISOString().slice(0, 10),
      service_type: "scheduled",
      cost: "",
      vendor: "",
      next_due_miles: "",
      next_due_hours: "",
      next_due_date: "",
      description: "",
    };
    expect(serviceDraftIncludes({ ...base, cost: "185" })).toBe(true);
    expect(serviceDraftIncludes({ ...base, vendor: "Bob's" })).toBe(true);
    expect(serviceDraftIncludes({ ...base, next_due_miles: "5000" })).toBe(true);
    expect(serviceDraftIncludes({ ...base, next_due_hours: "250" })).toBe(true);
    expect(serviceDraftIncludes({ ...base, next_due_date: "2026-12-04" })).toBe(true);
    expect(serviceDraftIncludes({ ...base, description: "oil change" })).toBe(true);
  });
});